name: CloudFormation Continue Update Rollback

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-west-2'
        type: string
      stack_name:
        description: 'Stack Name'
        required: true
        type: string
      resources_to_skip:
        description: 'Resources to Skip'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      MS_TEAMS_WEBHOOK_URI:
        required: false
jobs:
  deploy:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    steps:
    
    - name: Microsoft Teams Deploy Card
      uses: patrickpaulin/ms-teams-deploy-card@master
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        card-layout-exit: complete
        show-on-start: false
        custom-facts: |
          - name: Environment
            value: ${{ inputs.environment_name }}

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.region}}

    - run: aws cloudformation continue-update-rollback --stack-name ${{ inputs.stack_name}} --resources-to-skip ${{ inputs.resources_to_skip}}
