name: Node.js CI

on:
 workflow_call:
    inputs:
      workingDirectory:
        description: 'Working Directory'
        default: '.'
        type: string
      NODE_VERSIONS:
        description: 'The version(s) of node to run unit tests with'
        required: false
        type: string
        default: '14.x'
      region:
        description: 'AWS Region'
        type: string
        default: 'us-west-2'
      configureAwsCredentials:
        description: 'Configure AWS Credentials'
        type: boolean
        default: false
    secrets:
      JFROG_AUTH_TOKEN:
        required: true
      COVERAGE_REPORT_GIST_TOKEN:
        required: false        
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      SONAR_TOKEN:
        required: false
      DEPLOY_USER_GITHUB_TOKEN:
        required: false

jobs:
  build:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - ${{ inputs.NODE_VERSIONS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - if: ${{ inputs.configureAwsCredentials == true }}
        name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region}}

      - name: 'Create .npmrc'
        shell: bash
        run: |
          echo "Creating/Updating .npmrc in $PWD"
          # Create a new .npmrc if there isn't one there already
          [ ! -e .npmrc ] && echo "registry=https://moetech.jfrog.io/artifactory/api/npm/nucleus-npm/" > ~/.npmrc
          [ -e .npmrc ] && cp .npmrc ~/.npmrc && echo "" >> ~/.npmrc
          echo "_authToken = ${{ secrets.JFROG_AUTH_TOKEN }}" >> ~/.npmrc
          echo "always-auth = true" >> ~/.npmrc

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run test:coverage --if-present

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: my-custom-directory
          args: >
            -Dsonar.organization=mutual-of-enumclaw
            -Dsonar.projectKey=mutual-of-enumclaw_nucleus-issue
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources.exclusions=**/*.spec.ts,**/*.json      
        env:
          GITHUB_TOKEN:: ${{ secrets.DEPLOY_USER_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
